cask_args appdir: '/Applications'
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "mas"
brew "zsh"
brew "nodebrew"

cask "docker"
cask "docker-toolbox"
cask "github"
cask "google-chrome"
cask "google-japanese-ime"
cask "google-backup-and-sync"
cask "inkdrop"
cask "slack"
cask "visual-studio-code"
cask "1password"
cask "alfred"
cask "virtualbox"
cask "spotify"

mas "Xcode", id: 497799835
mas "LINE", id: 539883307
